# the desired pose of the tool 
geometry_msgs/PoseStamped pose

# lookahead distance 
float32 lookahead

# distance to goal pose to reach goal
float32 goal_cartesian_tolerance
float32 goal_quaternion_tolerance

# timeout for completing action
duration timeout


---
#result definition


---

#feedback

float32 cartesian_error
float32 quaternion_error
int32 fps

